### ISSUE TITLE
Paypal Donations are being rejected

### ISSUE THREAD

**Issue by cleary** [titilambert/nagvis#1]
Hi, 
I tried to make a donation to your project - I followed the instructions on [the website](https://www.nagvis.org/become-sponsor):

> You can easily donate using PayPal via the Sourceforge.net platform.

Sourceforge redirects me to this paypal link for lars@vertical-visions.de:
https://www.paypal.com/cgi-bin/webscr?item_name=Donation+to+NagVis&cmd=_donations&business=lars%40vertical-visions.de

Everything went through fine, but I just received a cancellation notice from Paypal:

> This payment was returned for the following reason(s):
> lars@vertical-visions.de did not sign up for a PayPal account or did not complete the registration process.

How can I make a donation to the project?

**Comment by titilambert** [comment]
Hello, This is NOT the official repository to nagvis. I do NOT know how to make donation
